name: Weekly Opportunities Email (Monday)

on:
  schedule:
    - cron: "0 0 * * 1" # Monday 00:00 UTC

  workflow_dispatch:

jobs:
  mail-opportunities:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Debug Url
        run: echo "${{ secrets.VERCEL_API_URL }}/api/v1/client-context/send-weekly-context-email/"

      - name: Send opportunities email
        run: |
          echo "Sending weekly opportunities email"
          curl -X GET \
            "${{ secrets.VERCEL_API_URL}}/api/v1/client-context/send-weekly-context-email/" \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            -w "HTTP Status: %{http_code}\n" \
            -s
