name: Daily Error Mailing

on:
  schedule:
    - cron: "0 3 * * *" # Run at 3:00 AM UTC
  workflow_dispatch:

jobs:
  mail-content:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Debug Url
        run: echo "${{ secrets.VERCEL_API_URL }}/api/v1/ideabank/cron/mail-daily-errors/"

      - name: Call api for mailing
        run: |
          echo "Mailing daily content error"
          curl -X GET \
            "${{ secrets.VERCEL_API_URL}}/api/v1/ideabank/cron/mail-daily-errors/" \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            -w "HTTP Status: %{http_code}\n" \
            -s
